### ISSUE TITLE
SevenZip.InvalidParamException: Invalid Parameter

### ISSUE THREAD

**Issue by Rombersoft** [squid-box/SevenZipSharp#100]
I added to archive 2 files using linux command
```tar -c --lzma -f foo.tar.lzma setup.exe archive.tar```
Also I can extract this foo.tar.lzma using linux file-roller application.
But When I try to extract using your library
I get error
```SevenZip.InvalidParamException: Invalid Parameter
  at SevenZip.Compression.LZMA.Decoder.SetDecoderProperties (System.Byte[] properties) [0x00029] in <789e29a422ee49be9f5a9bc9f6e5ab8f>:0 ```

This is my code

```
public static bool DecompressFromTarLzma(string file, string outputDirectory)
        {
            try
            {
                //extract from .lzma
                byte[] toDecompress = null;
                SevenZip.Compression.LZMA.Decoder decoder = new SevenZip.Compression.LZMA.Decoder();
                using (Stream strmInStream = new FileStream(file, FileMode.Open, FileAccess.Read))
                {
                    strmInStream.Seek(0, 0);
                    using (MemoryStream strmOutStream = new MemoryStream())
                    {
                        byte[] properties2 = new byte[5];
                        if (strmInStream.Read(properties2, 0, 5) != 5)
                            throw (new Exception("input .lzma is too short"));
                        long outSize = 0;
                        for (int i = 0; i < 8; i++)
                        {
                            int v = strmInStream.ReadByte();
                            if (v < 0)
                                throw (new Exception("Can't Read 1"));
                            outSize |= ((long)(byte)v) << (8 * i);
                        }
                        decoder.SetDecoderProperties(properties2);
                        long compressedSize = strmInStream.Length - strmInStream.Position;
                        decoder.Code(strmInStream, strmOutStream, compressedSize, outSize, null);
                        toDecompress = strmOutStream.ToArray();
                    }
                }

                //extract from tar из .tar
                using (Stream inStream = new MemoryStream(toDecompress))
                {
                    TarArchive tarArchive = TarArchive.CreateInputTarArchive(inStream);
                    tarArchive.ExtractContents(outputDirectory);
                    inStream.Close();
                }
                return true;
            }
            catch (Exception ex)
            {
                Logs.Updater.Error("failed unzip: {0}", ex.ToString());
                return false;
            }
        }
```
Maybe I use not right linux comand to archivation or you show me how to add several files to tar.lzma archive

**Comment by squid-box** [comment]
I'm sorry, I think you've got the wrong library. SevenZipSharp does not have the namespace `SevenZip.Compression`, or the `TarArchive` class.
