### ISSUE TITLE
 Creating unnamed folder when creating zip

### ISSUE THREAD

**Issue by Bongotainment** [squid-box/SevenZipSharp#102]
I tried to zip three files that I place in my temporary files directory (%temp%). When zipping them with SevenZipSharp I get a zip file with an unnamed folder in it. 
![image](https://user-images.githubusercontent.com/1878806/81663562-14bcf600-943f-11ea-9f22-fb461416b4a0.png)
Within this folder, the three files are shown correctly. 

The path to the directory is passed to my application via another library which provides the path in the 8.3 format. The path looks as follows "C:\Users\XKC-ML~1\AppData\Local\Temp\ApplicationFolder".
It seems that SevenZipSharp or 7Zip in general couldn't handle this path. 

I could resolve this issue by getting the full path via 
`archivePath = Path.GetFullPath(archivePath);`
Is this behavior by design?

**Comment by squid-box** [comment]
I don't see a reason this would be by design, and I've verified that 7z itself can handle SFN paths - but SevenZipSharp doesn't.

I'll look into it, but unless it's a very quick fix it'll likely be a while before I've got a solution.
