### ISSUE TITLE
File extraction hangs with a 32MB solid 7z file.

### ISSUE THREAD

**Issue by ebolefeysot** [squid-box/SevenZipSharp#107]
using (SevenZipExtractor szip = new SevenZipExtractor(testFile))
{
  szip.PreserveDirectoryStructure = false;
  var stream = new MemoryStream();
  szip.ExtractFile("002-p1.p1", stream);  //this works
  szip.ExtractFiles(".", "002-p1.p1");  //this hangs
}

ArchiveExtractCallback(271): _archive.GetProperty(index, ItemPropId.Path, ref data); never return.
Does it means something to you ?

I can post the 7z with a failing unit test, but it is 32MB. Tell me if it's possible.

I notice the archive is solid.
I manage to make it work by using streams 7zip methods with a fileStream.

**Comment by squid-box** [comment]
Sorry it's been nearly a year, but looking at this now I can't seem to reproduce it with a 7z file - I'm assuming there's some special condition on yours (all compressed 7z files should be solid btw).

It's odd that it works for you through the stream but not with ExtractFiles... 

If you can provide me with a file where this occurs, I can dig deeper.

**Comment by ebolefeysot** [comment]
I will look for a file...

**Comment by ebolefeysot** [comment]
Hi. I tried with 7z.dll v20 and 21 and can't reproduce the problem.

**Comment by squid-box** [comment]
OK, good to hear that it might be something that was solved on the 7-Zip side.
In that case I'll close this issue, but please re-open it if you find a way to reproduce the issue and I'll have another look!
