### ISSUE TITLE
Delete files after compression?

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [squid-box/SevenZipSharp#108]
7-Zip software has the option to delete files after compression. Is there such an option in SevenZipSharp?

**Comment by squid-box** [comment]
No, there is no such convenience option in SevenZipSharp, and I'm hesitant to start adding such things. Given how you'd likely use SevenZipSharp to compress files, it'd be fairly easy to implement yourself, and it's not really a core function of 7-Zip.
