### ISSUE TITLE
SevenZipExtractor unable to expand tar file

### ISSUE THREAD

**Issue by ewilansky** [squid-box/SevenZipSharp#114]
Using the tar file in your TestData directory (tar.tar), I'm unable to expand the tar:

```
using var stream = File.OpenRead(path);
using var zipExtractor = new SevenZip.SevenZipExtractor(stream);
var children = zipExtractor.ArchiveFileData;
```

throws at zipExtractor.ArchiveFileData:

Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.

I'm using latest (v 1.3.283)

**Comment by squid-box** [comment]
@ewilansky: This seems similar to #68 - are you using the full 7z.dll or just the 7za.dll variant? 7za only supports the 7z format.

**Comment by ewilansky** [comment]
I was using 7z.dll. However, since we needed cross-platform support, we switched to an extraction library that doesn't rely on 7z.dll.
