### ISSUE TITLE
UWP Build Error: MCG0037:InvalidCSharpIdentifierName 

### ISSUE THREAD

**Issue by comfr3ak** [squid-box/SevenZipSharp#122]
Receive error building in Visual Studio for UWP project:

Microsoft Visual Studio Community 2019
Version 16.9.3

C:\Users\XXXXXXXXX\.nuget\packages\microsoft.net.native.compiler\2.2.9-rel-29512-01\tools\Microsoft.NetNative.targets(805,5): error : MCG0037: MCG0037:InvalidCSharpIdentifierName Struct 'SevenZip.PropVariant' in assembly 'Assembly(Name=SevenZipSharp, Version=1.3.318.0, Culture=neutral, PublicKeyToken=c8ff6ba0184838bb)' has a field with name '<Value>k__BackingField' that is invalid. This could be because the name is obfuscated or the field is auto-implemented by the compiler. Please make sure the field name follows C# identifier conventions.

**Comment by squid-box** [comment]
A brief search on this seems to indicate this is a problem that's been around with the .NET Native compiler (used for UWP release) - for quite some time: https://github.com/microsoft/dotnet/issues/807 

The `k__BackingField` refers to auto-properties, and I'm a little hesitant to regress them into manually handling field-backed properties again.

I'll look into it and see how big changes would be needed to support UWP apps, if it isn't too big I'll fix it.

**Comment by squid-box** [comment]
This fix will be included in the next release: 1.4.0.
