### ISSUE TITLE
Cannot split archive into multiple files larger than 2GB

### ISSUE THREAD

**Issue by stefanof95** [squid-box/SevenZipSharp#124]
I'm trying to create a 7z archive splitted into multiple files of more than 2GB, but i have a problem since the class SevenZipCompressor VolumeSize property is a 32 bit integer.
Is it possible to change VolumeSize to long type to support more than 2GB?

**Comment by squid-box** [comment]
The VolumeSize property is internal to SevenZipSharp, so I see no reason it shouldn't be possible to simply change into a long instead.

**Comment by squid-box** [comment]
This will be included in the next release, 1.4.0.
