### ISSUE TITLE
Exclude file extensions when compressing directory

### ISSUE THREAD

**Issue by bpetersen1** [squid-box/SevenZipSharp#127]
Is it possible to exclude certain files or file types when compressing a directory?

I've tried adding in a custom parameter with the "x" switch but I keep getting the following error, "Value does not fall within the expected range."

Eg. of code used

Compressor.CustomParameters.Add("-xr!", $"'{folderName}\\{string.Join("; ",excludedFiles)}'");
foldername = Directory path (C:\customerdata)
excluded files is an array ["*.bak","*.zip"...etc]

-xr! 'C:\customerdata\*.bak; *.zip; *.7z; *.rar; *.7zip' is the final custom parameter.

And when I run Compressor.CompressDirectory(folderName, outPathname, password); it throws the above exception.

Any help would be much appreciated.

**Comment by squid-box** [comment]
I think you've misunderstood the switches/parameters in SevenZipSharp: They're custom [*compression* parameters](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm) - not a way to pass [switches](https://sevenzip.osdn.jp/chm/cmdline/switches/) to SevenZip itself.

In your case I'd probably use the `System.IO.Directory` methods to create a collection of filenames (with your exclusion filter applied) to compress and use `SevenZipCompressor.CompressFiles` to create the archive.

**Comment by bpetersen1** [comment]
I thought I had it wrong, Thanks so much for your response
