### ISSUE TITLE
Execution has failed due to an internal SevenZipSharp issue

### ISSUE THREAD

**Issue by Cicker21** [squid-box/SevenZipSharp#128]
I have recently tried compressing and unzipping files using the NuGet (https://www.nuget.org/packages/Squid-Box.SevenZipSharp/1.4.0.345?_src=template)
However I can't compress them, the error probably comes from the dll library. I have tried downloading 7zip in 32 bit and 64 bit, using both .dll but the error is the same, I can't think of anything to do.

Software Information:
Visual Studio 2019
Squid-Box.SevenZipSharp v1.4.0.345
7z.dll (64bits) 19.00 
7z.dll (32bits) 21.01 alpha

    

     private void Compress(string source, string output)
             {
             /*32-bits version*/  string path = Directory.GetCurrentDirectory() + @"\32-7z.dll";
            //64-bits version    string path = Directory.GetCurrentDirectory() + @"\64-7z.dll";
   
            SevenZipCompressor compressor = new SevenZipCompressor();
            compressor.ArchiveFormat = OutArchiveFormat.Zip;
            compressor.TempFolderPath = Path.GetTempPath();
            compressor.CompressionMode = SevenZip.CompressionMode.Create;
            compressor.CompressionLevel = SevenZip.CompressionLevel.Fast;
            compressor.CompressionMethod = CompressionMethod.Lzma2;
            compressor.ZipEncryptionMethod = ZipEncryptionMethod.Aes256;

            var assemblyDllPath = compressor.TempFolderPath + "32-7z.dll";
          //var assemblyDllPath = compressor.TempFolderPath + "64-7z.dll";
            File.Copy(path, assemblyDllPath, overwrite: true);
            SevenZipExtractor.SetLibraryPath(path);
            
            compressor.CompressDirectory(@"A:\C#\random", @"A:\C#\empty\archive.zip", "password");

        }
When im using the 32-bits dll, proyect is set as Debug x86.
When im using the 64-bits dll, proyect is set as Debug x64.

The error is the following in both cases: 
`
   SevenZip.SevenZipException
  HResult=0x80131500
  Message = Execution has failed due to an internal SevenZipSharp issue (0x80004001 / -2147467263).
  Please report it to https://github.com/squid-box/SevenZipSharp/issues/, include the release number, 7z version used, and attach  
  he archive.
  Source = SevenZipSharp
`
I don't know what file I'm supposed to add, so I'm waiting for answers
I really appreciate the time you put into this, thanks in advance.

**Comment by squid-box** [comment]
The error code you're getting (0x80004001) corresponds to the error "Not Implemented" - it comes from the fact that you're trying to use a CompressionMethod that is not supported by the .zip format.

Unless you have specific requirements I'd suggest using `CompressionMode.Default` - otherwise the following work with the .zip format:
* `CompressionMethod.Copy`
* `CompressionMethod.Deflate`
* `CompressionMethod.Deflate64`
* `CompressionMethod.BZip2`
* `CompressionMethod.Lzma`
* `CompressionMethod.Ppmd`
