### ISSUE TITLE
Unauthorized exception when extracting read only files

### ISSUE THREAD

**Issue by benjicoh** [squid-box/SevenZipSharp#131]
Should allow extraction of read only files

**Comment by benjicoh** [comment]
Problem is only for split streams the fix is easy and passes all test

In the ctor of InMultiStreamWrapper
change from :
`Streams.Add(new FileStream(fileName, FileMode.Open)`
to :
`Streams.Add(new FileStream(fileName, FileMode.Open, FileAccess.Read));`

Please commit it, if you can
Thanks, Benny

**Comment by squid-box** [comment]
Fixed by #157.
