### ISSUE TITLE
Multipart RAR5 archives fail to extract

### ISSUE THREAD

**Issue by fgimian** [squid-box/SevenZipSharp#170]
Creating a multipart RAR file using RAR5 compression and attempting to extract it with the latest release version of SevenZipSharp results in the following exception:

```
Unhandled exception. SevenZip.ExtractionFailedException: Could not extract files! Message: File is corrupted. Data error has occured.
   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
   at SevenZip.SevenZipExtractor.ExtractFile(Int32 index, Stream stream)
   at Program.<Main>$(String[] args) in C:\Users\Fots\source\MultiTest.SevenZipSharp\Program.cs:line 36
```

In the destination directory, only partial data of the file from the first volume is extracted.

I can verify that the same file extracts perfectly using the 7z CLI or WinRAR.

Thanks in advance!
Fotis

**Comment by fgimian** [comment]
Just an extra little bit of information in case it's helpful.  Extracting all files using `ExtractArchive` works correctly, but extracting individual files using `ExtractFile` with specific indexes or filenames causes trouble. 😄

**Comment by fgimian** [comment]
I've been working through this today and have discovered some interesting things about it.  I have a little test multipart RAR5 archive with 2 files contained within it.

Extracting it as follows works fine:

```c#
        SevenZipBase.SetLibraryPath(@"C:\Users\Fots\scoop\apps\7zip\22.01\7z.dll");
        using SevenZipExtractor extractor = new(archivePath);

        Console.WriteLine($"Extracting index 0");
        using (FileStream stream1 = File.Create("meow0.dat"))
        {
            extractor.ExtractFile(0, stream1);
        }

        Console.WriteLine($"Extracting index 1");
        using (FileStream stream2 = File.Create("meow1.dat"))
        {
            extractor.ExtractFile(1, stream2);
        }
```

However, when iterating through files and doing exactly the same thing, I encounter the error mentioned above:

```c#
        SevenZipBase.SetLibraryPath(@"C:\Users\Fots\scoop\apps\7zip\22.01\7z.dll");
        using SevenZipExtractor extractor = new(archivePath);

        foreach (ArchiveFileInfo entry in extractor.ArchiveFileData)
        {
            Console.WriteLine($"Extracting index {entry.Index}");
            using (FileStream stream = File.Create($"meow{entry.Index}.dat"))
            {
                extractor.ExtractFile(entry.Index, stream);
            }
        }
```

The problem occurs on the second file (i.e. index 1):

```
Extracting index 0
Extracting index 1
Unhandled exception. SevenZip.ExtractionFailedException: Could not extract files! Message: File is corrupted. Data error has occured.
   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e) in C:\Users\Fots\source\ideas\archive-tester\SevenZipSharp\SevenZip\SevenZipBase.cs:line 183
   at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler) in C:\Users\Fots\source\ideas\archive-tester\SevenZipSharp\SevenZip\SevenZipBase.cs:line 254
   at SevenZip.SevenZipExtractor.ExtractFile(Int32 index, Stream stream) in C:\Users\Fots\source\ideas\archive-tester\SevenZipSharp\SevenZip\SevenZipExtractor.cs:line 1099
   at ArchiveTester.Program.Main() in C:\Users\Fots\source\ideas\archive-tester\ArchiveTester\Program.cs:line 31
```

**Comment by fgimian** [comment]
After many hours of troubleshooting, I believe I've discovered the problem.  It appears that reusing the open callback function causes this issue.

Changing `GetArchiveOpenCallback` in `SevenZipExtractor` to the following resolves the issue:

```c#
        private ArchiveOpenCallback GetArchiveOpenCallback()
        {
            return _openCallback = string.IsNullOrEmpty(Password)
                ? new ArchiveOpenCallback(_fileName)
                : new ArchiveOpenCallback(_fileName, Password));
        }
```

If you feel this solution is adequate and makes sense in the scheme of the 7-Zip SDK, I'm happy to send a PR.  I have stumbled my way around today because I honestly don't understand the internals of the 7-Zip COM interface.

**Comment by fgimian** [comment]
Digging even deeper, I can see that the problem appears to have its origins in the `GetStream` method of `ArchiveOpenCallback`.  Specifically, the way that the class reuses `InStreamWrapper` in the `_wrappers` private member if it already exists.  The problem appears to be that the 7-Zip library may have seeked on this stream and thus the position being read at the time of extraction is incorrect.

The simplest solution I could come up with was ensuring we seek to the start when reusing a stream:

```c#
            if (_wrappers.ContainsKey(name))
            {
                inStream = _wrappers[name];
                // Ensure that we seek to the beginning of the stream when reusing it.
                inStream.Seek(0, SeekOrigin.Begin, IntPtr.Zero);
```

This appears to do the trick in my testing, but would love some thoughts from others too.  Of course an alternative is t o create a new `InStreamWrapper` no matter what, but then we will need to think about disposing the old one.

**Comment by Lombra** [comment]
Hello,

Hoping this can get merged, though the project does not really seem to be in active development right now?

I stumbled upon not only this issue, but also another where if I access the `IsSolid` property on the `SevenZipExtractor` before extracting (using `ExtractArchive`), the extraction will throw:
```
SevenZip.ExtractionFailedException: 'Could not extract files! Message: File is corrupted. Data error has occured.'
```
Seems to affect only RAR5 archives, though I've not verified whether it only affects segmented ones.

**Comment by fgimian** [comment]
I'll close this issue now that the PR is merged.
