### ISSUE TITLE
Windows Virus Scanner - Trojan:Win32/Wacatac.B!m in Squid-Box.SevenZipSharp Version=1.5.1.15

### ISSUE THREAD

**Issue by jonreis** [squid-box/SevenZipSharp#186]
I installed the latest nuget package and Windows has detected it as having a virus. Not sure if this is a false positive or not, but I have rolled back to the previous version.

file: C:\Development\HL7spy2021\HL7Spy\bin\Debug\net48\win\SevenZipSharp.dll

**Comment by squid-box** [comment]
I'd probably point to it being a false-positive - my Windows doesn't find anything there, and neither did VirusTotal

![image](https://user-images.githubusercontent.com/864820/227373472-a8ca81aa-4f42-4239-abd9-484b7f785f70.png)

It would be disturbing if that was the case, as the entire package is built through GitHub Actions, and it would mean that their build agents were infected.

I'll leave this issue open for a bit to see if others detect any problems, but I'm not very concerned at this point.

**Comment by squid-box** [comment]
No worries, I'm happy you immediately though to notify me :)
