### ISSUE TITLE
version 1.6.0.22 is unusable for extraction

### ISSUE THREAD

**Issue by yokrysty** [squid-box/SevenZipSharp#188]
i had no problems with version 1.5.2.21, but when i upgraded to 1.6.0.22 (which was the latest at time of writing) extraction stopped working

if running in Visual Studio **ExtractArchiveAsync** triggers:
`Managed Debugging Assistant 'RaceOnRCWCleanup' : 'An attempt has been made to free an RCW that is in use.  The RCW is in use on the active thread or another thread.  Attempting to free an in-use RCW can cause corruption or data loss.'`

and I get the exception message:
`Execution has failed due to an internal SevenZipSharp issue (0x80131502 / -2146233086).
Please report it to https://github.com/squid-box/SevenZipSharp/issues/, include the release number, 7z version used, and attach the archive.`

running **ExtractArchiveAsync Test** in debug breaks with exception, where ArchiveFileData seems to be empty
![image](https://user-images.githubusercontent.com/9500609/229379273-8a460ef1-0695-41a9-9f91-7a78f6870cfc.png)

I don't understand how it was published to nuget if unit tests failed

**Comment by squid-box** [comment]
Yup, you're correct - I managed to break this through a dumb autoformatting run.

The reason these tests weren't run during CI is because I've set them to be ignored due to being flaky when run on AppVeyor - as part of this fix I'm re-enabling them to see if GitHub Actions handles the tests better.

**Comment by yokrysty** [comment]
oh yeah i had to remove the ignore to run the test, but weird, i never had those kind of problems using ReSharper
