### ISSUE TITLE
ModifyArchive does not work on password protected archives

### ISSUE THREAD

**Issue by Vicharian** [squid-box/SevenZipSharp#19]
I want to rename and/or delete files from a 7z archive

When I use this code (i.e. no password) it works. It creates the zip. I can open it in 7zip and extract files, etc in the archive created in the first step. Also the first file is renamed and the second removed.

    Dim Compressor As New SevenZip.SevenZipCompressor
    Compressor.EncryptHeaders = True

    Compressor.CompressFiles("d:\temp\test.7z", {"D:\Temp\svg.txt", "D:\Temp\tmp.txt"})

    Dim NewList = New Dictionary(Of Integer, String)
    NewList.Add(0, "newsvg.txt")
    NewList.Add(1, Nothing)

    Compressor.ModifyArchive("d:\temp\test.7z", NewList)

But this code does not - throws exception complaining about wrong password. As with above, the archive created is fine -- just that ModifyArchive has trouble with it.

    Dim Compressor As New SevenZip.SevenZipCompressor
    Compressor.EncryptHeaders = True

    Compressor.CompressFilesEncrypted("d:\temp\test.7z", "password", {"D:\Temp\svg.txt", "D:\Temp\tmp.txt"})

    Dim NewList = New Dictionary(Of Integer, String)
    NewList.Add(0, "newsvg.txt")
    NewList.Add(1, Nothing)

    Compressor.ModifyArchive("d:\temp\test.7z", NewList, "password")

**Comment by Vicharian** [comment]
Thank you for looking into it. 

I did find that changing the following (line 1499)
` using (var extr = new SevenZipExtractor(archiveName))`

to
` using (var extr = new SevenZipExtractor(archiveName, password))`

made the code fail a little later :)
Wish I could figure it out completely

**Comment by squid-box** [comment]
The problem lies fairly deep into it all, I've managed to solve it, but in a very messy way (one I can't really release). I'll try to make a proper solution later tonight.

**Comment by Vicharian** [comment]
Works for me! Thanks for the quick turn-around on this.

**Comment by squid-box** [comment]
Happy to help, thanks for giving good clues to solve it :)

NuGet package 1.1.106should be available (listed) on NuGet.org soon.
