### ISSUE TITLE
Execution has failed due to an internal SevenZipSharp issue (0x800700ce / -2147024690).

### ISSUE THREAD

**Issue by captainphat** [squid-box/SevenZipSharp#193]
Hello, 

I have a script to unzip file.zip.zip..zip. But sometimes some files report error: Execution has failed due to an internal SevenZipSharp issue (0x800700ce / -2147024690).

i use Powershell to unzip

**Comment by squid-box** [comment]
The 0x800700CE error code indicates that there's an issue with the length of the filenames - I'd guess the resulting full path of your extracted files exceed what Windows allows.

I've added a more explicit exception message for this, but it's not really something I'd expect this library to try to mitigate.
