### ISSUE TITLE
Publishing a new release

### ISSUE THREAD

**Issue by fgimian** [squid-box/SevenZipSharp#207]
Hey there, so sorry to bother you, but I was wondering if you would kindly publish a new release which incorporates the fixes that I provided (which were already merged to the dev branch).

Thanks heaps
Fotis

**Comment by squid-box** [comment]
You have nothing to apologize for, sorry for dropping out without pushing a release. I have some details I need to figure out, then I'll push a new version.

**Comment by squid-box** [comment]
It's in the hands of Nuget.org now :)

![image](https://github.com/squid-box/SevenZipSharp/assets/864820/9923cb2a-3e04-4bca-8674-43dccf965f04)

Closing issue.
