### ISSUE TITLE
Fallout 4 - install error cbbe nmm

### ISSUE THREAD

**Issue by dalvin0531** [squid-box/SevenZipSharp#23]
Execution has failed due to an internal SevenZipSharp issue.  7zip version 18.5.0.0.

**Comment by squid-box** [comment]
@dalvin0531: Could you link me to the mod you're trying to install? 

And which version of NMM are you using? Do you have a trace log from when this problem occurs?

**Comment by dalvin0531** [comment]
https://www.nexusmods.com/fallout4/mods/15 , NMM version 0.65.10.0 as for trace log the only ones im seeing is from my c drive nmm. i have a seprate nmm for my d drive but i cant find the trace logs for it.

**Comment by dalvin0531** [comment]
Found the problem. I freed up some space on my c drive and that seemed to do the trick. Although i dont see why that had anything to do with my d drive and why the error didn't just say my c disk space was full. But anyways thanks for your help!

**Comment by squid-box** [comment]
@dalvin0531: Thanks for the last comment, from the next version (of SevenZipSharp, not NMM) it should be a bit clearer if there's not enough space for extraction.
