### ISSUE TITLE
Rename target folder

### ISSUE THREAD

**Issue by IrinaRazel** [squid-box/SevenZipSharp#35]
Hello, can I extract files changing filenames?

For example archive struct is: 
root/folder1/file.txt

I want at the end:
my folder/file.txt

**Comment by squid-box** [comment]
If you just want to ignore the directory structure in the archive, you can set the Extractor property PreserveDirectoryStructure to false and it will extract all files in the archive to the same directory. Just be careful that you don't have several files with the same name in the archive.

```
using (var extractor = new SevenZipExtractor("someArchive.7z"))
{
    extractor.PreserveDirectoryStructure = false;
    extractor.ExtractArchive("my folder");
}
```

**Comment by IrinaRazel** [comment]
no no, I need PreserveDirectoryStructure=true but extract it replacing root directory

**Comment by squid-box** [comment]
I'm not aware of any such feature, but you could likely achieve this by handling each extracted file and rename/move it after extraction.

Either by unpacking to a temporary directory and moving the files, or look into using the Extractor events `FileExtractionStarted` or `FileExtractionFinished`.

**Comment by IrinaRazel** [comment]
`FileExtractionStarted` or `FileExtractionFinished` not available to modify FileName property, it is readonly

**Comment by squid-box** [comment]
Then you'll have to rename them manually after extraction.

**Comment by IrinaRazel** [comment]
Can you include this feauture in library?

**Comment by squid-box** [comment]
I don't see why I would, it seems to be a very niche request to rewrite part of the path of a structured archive.

Feel free to propose a pull request with the added functionality, but I won't spend time implementing this for you.

**Comment by IrinaRazel** [comment]
ok, I just will delete this dll from my project. No need any projects with shit support.
