### ISSUE TITLE
Feature Request : Detect if the archive is first volume in multi part rar archive.

### ISSUE THREAD

**Issue by ravibpatel** [squid-box/SevenZipSharp#37]
Currently, SevenZipSharp doesn't detect if the archive is the first volume of the multi-part archive. In the case of RAR archives, it is necessary cause all parts have the file extension of ".rar".

Currently, I determine it using the file name of the archive.

```csharp
bool isVolume =
sevenZipExtractor.ArchiveProperties.Any(x =>
	x.Name.Equals("IsVolume") && x.Value != null && x.Value.Equals(true));
if (isVolume)
{
	var split = fileInfo.FullName.Split('.');
	if (split.Length >= 3)
	{
		if (split[split.Length - 2].StartsWith("part"))
		{
			int.TryParse(split[split.Length - 2].Substring(4), out var volumeNumber);
			if (volumeNumber != 1)
			{
				throw new Exception("Not the first volume of the archive.");
			}
		}
	}
}
```

Is it possible add a feature using file headers ([Volume Number under Main Archive Header](https://www.rarlab.com/technote.htm#mainhead)) that can tell us if the current archive is the first volume or not?

**Comment by ravibpatel** [comment]
I found the solution to the problem. If I open a pull request can you merge it?

**Comment by squid-box** [comment]
Sorry for the silence, it's been a busy week (and coming weeks as well it seems).

If your solution is decent, and doesn't change any existing public method signatures (I'm fine with extending existing ones, or adding new ones if they make sense) I'll gladly include it.

Try me and we'll discuss it ;)

**Comment by ravibpatel** [comment]
I added the pull request #38 for this feature.

**Comment by squid-box** [comment]
Once validated by NuGet, 1.1.136 will include your changes - I assume this fixes this issue for you?

**Comment by ravibpatel** [comment]
Yes, Thanks for merging it. I will look into the tar.gz problem too and I will open a pull request if it is a clean solution and up to the standard.
