### ISSUE TITLE
Use IDictionary instead of Dictionary for increased flexibility

### ISSUE THREAD

**Issue by rotvel** [squid-box/SevenZipSharp#42]
Using IDictionary as parameter to CompressStream|FileDictionary would give us the possbility to pass a SortedDictionary or ConcurrentDictionary directly to those methods.

I have a feature branch - https://github.com/squid-box/SevenZipSharp/pull/41 - with the proposed changes. Please review and let me know if you find it useful.

**Comment by squid-box** [comment]
This will be available in 1.1.144, should be verified on NuGet.org shortly.

Thanks for the PR!

**Comment by rotvel** [comment]
Thank you.
