### ISSUE TITLE
High memory use and hang on large archives with current versions of 7Z.dll

### ISSUE THREAD

**Issue by mdmadonna** [squid-box/SevenZipSharp#43]
I have a simple program that extracts entire archives of 7zip files.  The archives contain video files so they tend to be large.  My test archive is about 700MB and contains 119 video files.  During testing, this simple loop:

    for (var i = 0; i < extractor.ArchiveFileData.Count; i++)
    {            
        extractor.ExtractFiles(BaseDirClass, extractor.ArchiveFileData[i].Index);
     }

extracted 28 files and consistently hung on the 29th file.  Memory utilization climbed to about 500MB (working set) before hang.  Hang occurs at the same spot using 32-bit or 64-bit and also occurs when running from the command line or within the VS debugger.  I tried ExtractALL
(i.e. extractor.ExtractArchive(BaseDirClass);) and got the same result at the same spot but the Working set shot up to about 2GB before the hang.  Poked around a bit and determined that the problem appeared to be 7z.dll. I was using V19.0 of 7z.dll.  Just for kicks, I tried 7za.dll and 7zxa.dll  - same results.  I then backpedaled a bit and tried V18.5 and got the same results.  I gave it one more shot with V16.4 of 7z.dll and that worked just fine.  The working set never got above 110MB.

Probably not much you can do about this but I thought I'd post this in case someone else runs into the same issue.

**Comment by MrM40** [comment]
Do you see the same issue with the standalone 7zip application or only when used with the SevenZipSharp wrapper?

**Comment by mdmadonna** [comment]
Haven't tried a new version of 7zip standalone. I am away from computers
right now but I will try when I return on Tuesday

**Comment by mdmadonna** [comment]
I decompressed the file using standalone 7Zip V19.  The Working Set rose steadily until it reached approx. 1.5GB when roughly 50% of the archive had been decompressed.  At that point the Working Set stopped growing and 7Zip continued to run and decompressed the file successfully.  Using 7Zip V16, the working set never exceeded 32MB.

The archive being decompressed was 949MB compressed and 1.08GB uncompressed.  It contained mostly videos (.mp4).  All testing was executed with 64-bit versions of 7Zip on a machine with Xeon processors and 48GB of memory

**Comment by MrM40** [comment]
Hmmm, doesn't sound good, especcially if you don't get anything in return for the massive increased memory use like better performance. I wounder if it is related to this issue writton by Igor himself "[Windows 10 : BUG : Large Pages](https://sourceforge.net/p/sevenzip/discussion/45797/thread/d3ee3821b0/)"

**Comment by mdmadonna** [comment]
I wish I had more time to investigate but hard-pressed right now.  I saw no speed improvement between V16 and V19 as both versions took about two minutes to decompress the archive.  I do not have large page support enabled so I'm not sure if Igor's note applies.  For the time being, I'll continue to use V16 7z.dll with SevenZipSharp and come back to this when I have more time.

**Comment by mdmadonna** [comment]
Changing issue heading from 'memory leak' to 'high memory use'.  Not sure if it was clear from the notes but this issue is not a memory leak but appears to be by design.

**Comment by MrM40** [comment]
OK....good to hear

**Comment by squid-box** [comment]
Sorry for hanging out in the background - with the limited time I have to work on this project I've let this lie. Even though it seems (to me) that there's not much to do on the SevenZipSharp side, I'll leave the issue open if you want to investigate further later.

**Comment by mdmadonna** [comment]
I will take a look at it but I am buried right now and will be through the end of August.

 

Marcel Madonna
Director

ajm Software 

PO Box 5405  

Plymouth, MI 48170

Office: 734.404.8621  I  Mobile: 734.377.5316 

 

Software, Service, Satisfaction

LEGAL DISCLAIMER 
The information contained in this communication is highly confidential and is intended solely for the use of the individual(s) to whom this communication is directed. If you are not the intended recipient, you are hereby notified that any viewing, copying, disclosure or distribution of this information is prohibited. Please notify the sender, by electronic mail or telephone, of any unintended receipt and delete the original message without making any copies.

ajm Software is a Michigan Limited Liability Company.

**Comment by mdmadonna** [comment]
I am going to close this item as I cannot spend amy more time with this.  I am just running into too many issues with 7z and have elected not to use it (probably something I am doing wrong).  Additionally, it sounds similar to issue #60 so maybe it will continue to be researched under that issue.
