### ISSUE TITLE
Excessive garbage collection during extraction

### ISSUE THREAD

**Issue by Moralis** [squid-box/SevenZipSharp#72]
Hello, @squid-box! I've notified huge performance degradation in case of a lot of small compressed files. Huge archive with real data (32gb uncompressed, 250k mostly small entries, something like compressed hard disk image) decompression is 4-12 times slower than with regular 7z.FM.exe, the main reason is excessive GC.Collect call in ArchiveExtractCallback.SetOperationResult (line 462) for each file. Test runs on such files show that ~70% of extraction time was spend in GC.Collect() call in our test case, our custom code allocates ~10kb of objects per second and 30-200 GC calls per second makes app suffer.
You can easily reproduce it with a lot of simple text files in one archive, I can send such if necessary.
Anyway it's weird that library collects garbage while it should be on application side, I've checked unzipping without GC calls and with different 7z archive content type and everything ok.

Probably reason of https://github.com/squid-box/SevenZipSharp/issues/46 is the same ArchiveUpdateCallback.SetOperationResult (line 709).

Thanks!

**Comment by squid-box** [comment]
Closing issue assuming it was addressed by #75 - please re-open if you're still seeing performance issues.
