### ISSUE TITLE
myx not supported due to missing conversion to int in SevenZipCompressor

### ISSUE THREAD

**Issue by Mgamerz** [squid-box/SevenZipSharp#73]
~~I am trying to compress an archive and I have been using the Ultra compression setting. I am porting code from an old program that used 7z on the command line with a -md=256m (which is 2^28). mx9 (ultra) is only 64MB dictionary, which when compressing my archive is the difference between a 29MB  (256MB dictionary) archive and a 59MB archive (64MB dictionary)~~

~~I have tried compressor.CustomParameters.Add("d", "28") but I get an invalid argument exception when the properties are set to the 7z binded dll. The d parameter is converted to an int so I can't use 256m for example. I can't find any tests or anything in the code for this project on how to use a custom dictionary size, which is really important for the kind of work that I am doing.~~

~~Anyone know how to do that? (I am using 7z LZMA).~~

My issue was that myx was not implemented. After doing some debugging it is due to the parameter binding not being cast to int before binding (instead binding as string).

https://github.com/squid-box/SevenZipSharp/blob/dev/SevenZip/SevenZipCompressor.cs#L313

On this line if you add a || pair.Key == "yx" on the end it fixes it. I might put a in a PR when I have time (I have a custom version of this library in my project so it takes more effort to put a PR back).

Once casted to an integer, yx works.

**Comment by Mgamerz** [comment]
Ah, my bad. The command I listed does actually work - another one I was using, (m)yx=9 doesn't seem to work. Not sure how big of a loss that is though.

**Comment by Mgamerz** [comment]
I updated the first post with info on how to fix missing yx support.

**Comment by squid-box** [comment]
@Mgamerz : Sorry for the delay, I (think I) accidentally fixed this while looking into another bug - please try with 1.2.258 when you have time and see if it works better.
