### ISSUE TITLE
Can't use custom parameter "d"

### ISSUE THREAD

**Issue by squid-box** [squid-box/SevenZipSharp#86]
As part of fixing #82, I've found that the "d" parameter ([see documentation for uses](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm)) also doesn't work. The solution to #82 has not resolved this one, so I'm adding it here as a Known Issue.

The unit test `SevenZipCompressorTests.CompressWithCustomParameters_BZip2` exposes this bug, but is marked as a warning for now.

This snippet shows the issue:
```
var compressor = new SevenZipCompressor
{
    ArchiveFormat = OutArchiveFormat.Zip,
    CompressionMethod = CompressionMethod.BZip2
};

compressor.CustomParameters.Add("d", "900000");
compressor.CompressFiles("path_to_archive, "path_to_file(s)_to_compress");
```

**Comment by shodiwarmic** [comment]
From the documentation you linked it appears the value you are passing is too large. Since you aren't specifying a symbol it is using a value of 2^900000 which is well above the maximum value.

> **d={Size}[b|k|m]**
>        Sets the Dictionary size for BZip2. You must specify the size in bytes, kilobytes, or megabytes. The maximum value for the Dictionary size is 900000b. If you do not specify any symbol from set [b|k|m], dictionary size will be calculated as DictionarySize = 2^Size bytes.

**Comment by squid-box** [comment]
Thanks, not sure how I misread the documentation that badly...
