### ISSUE TITLE
How to use multithreaded compression?

### ISSUE THREAD

**Issue by PupilStudio** [squid-box/SevenZipSharp#92]
Are there any propety to set it?

**Comment by squid-box** [comment]
As long as the chosen compression method supports it, you need to add it as a custom parameter to your SevenZipCompressor object. You can read more on custom parameters here: https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm

Typically you'd add something like `mt=on` or `mt=4` depending on your requirements/environment.

**Comment by squid-box** [comment]
You can also check the [SevenZipCompressorCustomParameterTests ](https://github.com/squid-box/SevenZipSharp/blob/dev/SevenZip.Tests/SevenZipCompressorCustomParameterTests.cs) class for examples on how to set this custom parameters. 

Eg. [SevenZipCompressorCustomParameterTests:57](https://github.com/squid-box/SevenZipSharp/blob/dev/SevenZip.Tests/SevenZipCompressorCustomParameterTests.cs#L57)

**Comment by PupilStudio** [comment]
Oh, thank you. It's work.
